filebeat:
  image: chenghuizhang/filebeat:latest
  restart: unless-stopped
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  environment:
   - LOGSTASH_HOST=172.17.10.114
   - LOGSTASH_PORT=5044
   - SHIPPER_NAME=aWonderfulName
